jewellery_project/Controllers/adminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jewellery_project.Models;
using System.IO;

namespace jewellery_project.Controllers
{
    public class adminController : Controller
    {

        jewellary_dbEntities1 db = new jewellary_dbEntities1();
        //
        // GET: /admin/
        public ActionResult Dashboard()
        {
            if (Session["fname"] != null)
            {

                var dt = (from j in db.tbl_user select j).ToList();
                int scount = 0;
                Session["ucount"] = dt.Count();
                var dt2 = (from j in db.tbl_order select j).ToList();
                foreach (var item in dt2)
                {
                    scount = scount + Convert.ToInt32(item.grandtotal);
                }
                Session["scount"] = scount;
                var dt3 = (from j in db.tbl_order select j).ToList();
                Session["ocount"] = dt3.Count();
                var dt4 = (from j in db.tbl_product select j).ToList();
                Session["stockcount"] = dt4.Count();
                Admin ss = new Admin();
                binddata_temp(ss);
                return View(ss);

            }
            else
            {
                return RedirectToAction("Login");

            }
        }
        //-------------------------login------------------------------
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Admin ss)
        {
            var obj = db.tbl_admin.Where(a => a.email.Equals(ss.email) && a.password.Equals(ss.password)).FirstOrDefault();
            if (obj != null)
            {
                Session["fname"] = obj.fname;
                Session["lname"] = obj.lname;
                Session["email"] = obj.email;
                return RedirectToAction("Dashboard");
            }
            else
            {
                Response.Write("<script>alert('Email Or Password Not Valid')</script>");

            }
            return View(ss);

        }
       
        public ActionResult Logout()
        {

            Session.Clear();
            return View("Login");
        }
        //---------------------------state---------------------
        [HttpGet]
        public ActionResult State()
        {
            if (Session["fname"] != null)
            {

                Admin ss = new Admin();
                binddata_state(ss);
                binddata_temp(ss);

                return View(ss);
            }
            else
            {
                return RedirectToAction("Login");
            }
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult State(Admin ss)
        {

            if (ss.s_id == 0)
            {
                tbl_state dt = new tbl_state();
                dt.name = ss.name;
                dt.DOC = System.DateTime.Now;
                dt.DOM = System.DateTime.Now;
                db.tbl_state.Add(dt);

                db.SaveChanges();


            }
            else
            {
                var dt = (from j in db.tbl_state where j.state_id == ss.s_id select j).FirstOrDefault();
                dt.name = ss.name;

                dt.DOM = System.DateTime.Now;

                db.SaveChanges();
            }

            binddata_state(ss);
            binddata_temp(ss);

            return RedirectToAction("State", ss);




        }
        private void binddata_state(Admin ss)
        {
            List<Admin> lc = new List<Admin>();
            List<tbl_state> ll = db.tbl_state.ToList();
            foreach (var item in ll)
            {
                Admin cc = new Admin();
                cc.s_id = item.state_id;
                cc.name = item.name;
                cc.DOC = item.DOC;
                cc.DOM = item.DOM;

                lc.Add(cc);
            }
            ss.rj = lc;
        }
        [HttpGet]
        public ActionResult Edit_state(int id)
        {
            Admin ss = new Admin();
            var dt = (from j in db.tbl_state where j.state_id == id select j).FirstOrDefault();
            ss.s_id = dt.state_id;
            ss.name = dt.name;

            binddata_state(ss);
            binddata_temp(ss);

            return View("State", ss);
        }
        [HttpGet]
        public ActionResult Delete_state(int id)
        {
            Admin ss = new Admin();
            var dt1 = db.tbl_state.Where(x => x.state_id == id).FirstOrDefault();
            db.tbl_state.Remove(dt1);
            db.SaveChanges();
            binddata_temp(ss);

            return RedirectToAction("State", ss);
        }
        /*------------------city Details-------------*/
        private void stateBind(Admin ss)
        {
            ss.states = new List<SelectListItem>();

            List<tbl_state> lc = db.tbl_state.ToList();
            foreach (var item in lc)
            {
                SelectListItem l = new SelectListItem();
                l.Text = item.name;
                l.Value = item.state_id.ToString();
                ss.states.Add(l);
            }
        }
        public ActionResult City()
        {
            if (Session["fname"] != null)
            {
                Admin ss = new Admin();
                stateBind(ss);

                binddata_city(ss);
                binddata_temp(ss);

                return View(ss);
            }
            else
            {
                return RedirectToAction("Login");

            }


        }


        [HttpPost]
        public ActionResult City(Admin ss)
        {

            if (ss.c_id == 0)
            {
                tbl_city dt = new tbl_city();
                dt.state_id = ss.st_id;
                dt.name = ss.cname;
                dt.DOC = System.DateTime.Now;
                dt.DOM = System.DateTime.Now;
                db.tbl_city.Add(dt);
                db.SaveChanges();
            }
            else
            {
                var dt = (from j in db.tbl_city where j.city_id == ss.c_id select j).FirstOrDefault();
                dt.state_id = ss.st_id;
                dt.name = ss.cname;

                dt.DOM = System.DateTime.Now;
                db.SaveChanges();
            }

            stateBind(ss);
            binddata_city(ss);
            binddata_temp(ss);

            return RedirectToAction("City", ss);
            // return View(ss);


        }

        private void binddata_city(Admin ss)
        {
            List<Admin> lc = new List<Admin>();
            // List<tbl_city> ll = db.tbl_city.ToList();
            var dt = (from j in db.tbl_city
                      join
                          k in db.tbl_state on j.state_id equals k.state_id

                      select new
                      {
                          c_id = j.city_id,
                          id = j.state_id,
                          state = k.name,
                          city = j.name,
                          DOC = j.DOC,
                          DOM = j.DOM

                      }).ToList();
            foreach (var item in dt)
            {
                Admin cc = new Admin();

                cc.name = item.state;
                cc.c_id = item.c_id;
                cc.cname = item.city;
                cc.cDOC = item.DOC;
                cc.cDOM = item.DOM;

                lc.Add(cc);
            }
            ss.rj = lc;
        }


        [HttpGet]
        public ActionResult Edit_city(int id)
        {
            Admin ss = new Admin();
            var dt = (from j in db.tbl_city where j.city_id == id select j).FirstOrDefault();
            ss.c_id = dt.city_id;
            ss.st_id = dt.state_id;
            ss.cname = dt.name;

            binddata_city(ss);
            stateBind(ss);
            binddata_temp(ss);

            return View("City", ss);
        }

        [HttpGet]
        public ActionResult Delete_city(int id)
        {
            Admin ss = new Admin();
            var dt1 = db.tbl_city.Where(x => x.city_id == id).FirstOrDefault();
            db.tbl_city.Remove(dt1);
            db.SaveChanges();
            binddata_temp(ss);

            return RedirectToAction("City", ss);
        }


        //           /*-------------------------Category Details -------------------*/
        public ActionResult Category()
        {

            if (Session["fname"] != null)
            {
                Admin ss = new Admin();
                binddata_category(ss);
                binddata_temp(ss);

                return View(ss);
            }
            else
            {
                return RedirectToAction("Login");

            }


        }

        [HttpPost]
        public ActionResult Category(Admin sa)
        {

            if (sa.cat_id == 0)
            {
                tbl_category dt = new tbl_category();
                dt.name = sa.cat_name;
                dt.DOC = System.DateTime.Now;
                dt.DOM = System.DateTime.Now;
                db.tbl_category.Add(dt);
                db.SaveChanges();
                ModelState.Clear();
            }
            else
            {
                var dt = (from j in db.tbl_category where j.cat_id == sa.cat_id select j).FirstOrDefault();
                dt.name = sa.cat_name;
                dt.DOM = System.DateTime.Now;
                db.SaveChanges();
            }


            Admin ss = new Admin();
            binddata_category(ss);
            binddata_temp(ss);

            return View("Category", ss);
            // return View(ss);

jewellery_project/Views/admin/Category.cshtml
@model jewellery_project.Models.Admin
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/admin_master.cshtml";
}

@using (Html.BeginForm("Category", "admin", FormMethod.Post))
{
      @Html.HiddenFor(m => m.cat_id)
    <section id="main-content">
        <section class="wrapper">
            <div class="form-w3layouts">
                <!-- page start-->
                <!-- page start-->
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">
                                Category
                            </header>
                            <div class="panel-body">
                                <div class="position-center">
                                    <form role="form">

                                        <div class="form-group">
                                            <label for="state">Category</label>
                                           
                                            @Html.TextBoxFor(m => m.cat_name, new { @class = "form-control" , @required=""})
                                            @Html.ValidationMessageFor(m=> m.cat_name)
                                            <br />
                                        </div>
                                        <input type="submit" class="btn btn-info" value="Submit">
                                      
                                    </form>
                                </div>

                            </div>
                        </section>

                    </div>

                </div>


                <!-- page end-->
            </div>
            <div class="table-agile-info">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Category table
                    </div>
                    <div>
                        <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
                            <thead>
                                <tr>
                                    <th data-breakpoints="xs">ID</th>
                                    <th>Category Name</th>
                                    <th data-breakpoints="xs">DOC</th>

                                    <th data-breakpoints="xs sm md" data-title="DOB">DOM</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.rj)
                                {
                                    <tr data-expanded="true">
                                        <td>@item.cat_id</td>
                                        <td>@item.cat_name</td>
                                        <td>@item.cat_DOC</td>
                                        <td>@item.cat_DOM</td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit_category", new { @id = item.cat_id })
                                        </td>
                                        <td>
                                            @Html.ActionLink("Delete", "Delete_category", new { @id = item.cat_id })
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>

    </section>

}


jewellery_project/Views/admin/City.cshtml
@model  jewellery_project.Models.Admin

@{
    ViewBag.Title = "City";
    Layout = "~/Views/Shared/admin_master.cshtml";
}
@using (Html.BeginForm("City", "admin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
   
       @Html.AntiForgeryToken()  
     @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
     @Html.HiddenFor(m => m.c_id)
    <section id="main-content">
        <section class="wrapper">
            <div class="form-w3layouts">
                <!-- page start-->
                <!-- page start-->
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">
                                City
                            </header>
                            <div class="panel-body">
                                <div class="position-center">
                                    <form role="form">
                                        <div class="form-group">
                                            <label for="state">State</label>
                                            @*<input type="text" class="form-control" id="state" placeholder="Enter state">*@
                                          
                                            @Html.DropDownListFor(m => m.st_id, Model.states as List<SelectListItem>, "--Select State--", new { @class = "form-control", @required = "" })
                                            @Html.ValidationMessageFor(m=> m.st_id, "", new { @class = "text-danger" })                                            
                                        
                                         </div>

                                        <div class="form-group">
                                            <label for="state">City</label>
                                            @*<input type="text" class="form-control" id="state" placeholder="Enter state">*@
                                            @Html.TextBoxFor(m => m.cname, new { @class = "form-control", @required = "" })
                                            @Html.ValidationMessageFor(m => m.cname, "", new { @class = "text-danger" })
                                            
                                        </div>



                                        <input type="submit" class="btn btn-info" value="Submit">
                                        @*<button type="submit" class="btn btn-info">Submit</button>*@
                                    </form>
                                </div>

                            </div>
                        </section>

                    </div>

                </div>


                <!-- page end-->
            </div>
            <div class="table-agile-info">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        City table
                    </div>
                    <div>
                        <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
                            <thead>
                                <tr>
                                    <th data-breakpoints="xs">ID</th>
                                    <th>State Name</th>
                                    <th>City Name</th>
                                    <th data-breakpoints="xs">DOC</th>

                                    <th data-breakpoints="xs sm md" data-title="DOB">DOM</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.rj)
                                {
                                    <tr data-expanded="true">

                                        <td>@item.c_id</td>
                                        <td>@item.name</td>
                                        <td>@item.cname</td>
                                        <td>@item.cDOC</td>
                                        <td>@item.cDOM</td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit_city", new { @id = item.c_id })
                                        </td>
                                        <td>
                                            @Html.ActionLink("Delete", "Delete_city", new { @id = item.c_id })
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>

    </section>
}





jewellery_project/Views/admin/Collection.cshtml
@model jewellery_project.Models.Admin

@{
    ViewBag.Title = "Collection";
    Layout = "~/Views/Shared/admin_master.cshtml";
}

@using (Html.BeginForm("Collection", "admin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
   
     
       @Html.AntiForgeryToken()    
     @Html.ValidationSummary(true, "", new { @class = "text-danger" }) 
     @Html.HiddenFor(m=> m.col_id)
    <section id="main-content">
        <section class="wrapper">
            <div class="form-w3layouts">
                <!-- page start-->
                <!-- page start-->
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">
                                Collection
                            </header>
                            <div class="panel-body">
                                <div class="position-center">
                                    <form role="form">

                                        <div class="form-group">
                                            <label for="state">Collection</label>
                                            @*<input type="text" class="form-control" id="state" placeholder="Enter state">*@
                                            @Html.TextBoxFor(m => m.col_name, new { @class = "form-control", @required = "" })

                                        </div>



                                        <input type="submit" class="btn btn-info" value="Submit">
                                        @*<button type="submit" class="btn btn-info">Submit</button>*@
                                    </form>
                                </div>

                            </div>
                        </section>

                    </div>

                </div>


                <!-- page end-->
            </div>
            <div class="table-agile-info">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Collection table
                    </div>
                    <div>
                        <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
                            <thead>
                                <tr>
                                    <th data-breakpoints="xs">ID</th>
                                    <th>Collection</th>
                                    <th data-breakpoints="xs">DOC</th>

                                    <th data-breakpoints="xs sm md" data-title="DOB">DOM</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.rj)
                                {
                                    <tr data-expanded="true">
                                        <td>@item.col_id</td>
                                        <td>@item.col_name</td>
                                        <td>@item.col_DOC</td>
                                        <td>@item.col_DOM</td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit_col", new { @id = item.col_id })
                                        </td>
                                        <td>
                                            @Html.ActionLink("Delete", "Delete_col", new { @id = item.col_id })
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>

    </section>
}



jewellery_project/Views/admin/Index.cshtml
@model jewellery_project.Models.kk
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/admin_master.cshtml";
}

<h2 style="background-color:white;">Index</h2>
@using (Html.BeginForm("Index","admin"))
{ 
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-denger" })
   @Html.TextBoxFor(m => m.name, new { @class="form-control",@placeholder="name"})
    <br />
    <input type="submit" value="add" />
}


jewellery_project/Views/admin/Order.cshtml
@model jewellery_project.Models.Admin
@{
    ViewBag.Title = "Order";
    Layout = "~/Views/Shared/admin_master.cshtml";
}

@Html.HiddenFor(m => m.order_id)

<section id="main-content">
    <section class="wrapper">

        <div class="table-agile-info">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Order Details
                </div>
                <div>
                    <table class="table" style="z-index:2">

                        <tr>
                            <th data-breakpoints="xs">Order ID</th>
                            <th>User Id</th>
                            <th>Status</th>

                            <th>Details</th>

                        </tr>

                        @foreach (var item in Model.rjd)
                        {
                            <tr>
                                <td>@item.order_id</td>
                                <td>@item.user_id</td>
                                <td>@item.status</td>

                                <td>
                                    <a href="@Url.Action("editorder", "admin", new { @id = item.order_id })" data-toggle="modal" data-target="#myModal">Details</a>
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </section>

</section>



<!-- Modal -->
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.js"></script>

<div class="modal fade" id="myModal" style="margin-top:10%;">
    @Html.Partial("orderedit")
</div>


jewellery_project/Views/admin/State.cshtml
@model jewellery_project.Models.Admin
@{
    ViewBag.Title = "State";
    Layout = "~/Views/Shared/admin_master.cshtml";
}

@using (Html.BeginForm("State", "admin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    
     @Html.AntiForgeryToken()  
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   @Html.HiddenFor(m => m.s_id)
 <section id="main-content">
        <section class="wrapper">
          <div class="form-w3layouts">
    <!-- page start-->
    <!-- page start-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    State
                </header>
                <div class="panel-body">
                    <div class="position-center">
                                <form role="form">

                                        <div class="form-group">
                                            <label for="state">State</label>
                                            @*<input type="text" class="form-control" id="state" placeholder="Enter state">*@
                                            @Html.TextBoxFor(m => m.name, new { @class = "form-control", @required="" } )
                                        </div>



                                        <input type="submit" class="btn btn-info" value="Submit">
                                        @*<button type="submit" class="btn btn-info">Submit</button>*@
                                    </form>
                                </div>

                            </div>
                        </section>

                    </div>

                </div>


                 @*page end*@
            </div>
            <div class="table-agile-info">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        State table
                    </div>
                    <div>
                        <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
                            <thead>
                                <tr>
                                    <th data-breakpoints="xs">ID</th>
                                    <th>State Name</th>
                                    <th data-breakpoints="xs">DOC</th>

                                    <th data-breakpoints="xs sm md" data-title="DOB">DOM</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.rj)
                                {
                                    <tr data-expanded="true">
                                        <td>@item.s_id</td>
                                        <td>@item.name</td>
                                        <td>@item.DOC</td>
                                        <td>@item.DOM</td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit_state", new { @id = item.s_id })
                                    </td>
                                        <td>@Html.ActionLink("Delete", "Delete_state", new { @id = item.s_id })
                                        </td>
                            </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>

    </section>

}

jewellery_project/Views/admin/stockedit.cshtml
@model jewellery_project.Models.Admin

@using (Html.BeginForm("Stock","admin",FormMethod.Post))
{ 
    <div class="container" style="background-color:white; width:40%; border-radius:10px; margin:auto;">
        <br />
        @Html.HiddenFor(m=>m.stock_id)
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-9">
                <div class="row">
                    <a href="#" data-dismiss="modal" class="close">&times;</a>
                </div>
                <br />
               
                <div class="row">
                    <label for="poffer">Product</label>
                    @Html.TextBoxFor(m => m.product_nm, new { @class = "form-control", @id = "disabledInput", @disabled = "" })
                </div>
                <div class="row">
                    <label for="poffer">Stock</label>
                    @Html.TextBoxFor(m => m.stock, new { @class = "form-control", @required = "" })
                </div>
                
                <br />
                <div class="row">

                    <input type="submit"  name="command" value="Save Change" class="btn btn-primary" />
                </div>
            </div>
            <div class="col-sm-1"></div>
        </div>
        <br />
    </div>
    
}