jewellery_project/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace jewellery_project.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

jewellery_project/Controllers/User_newController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jewellery_project.Models;
using CaptchaMvc.HtmlHelpers;
using System.Net;
using System.Net.Mail;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;


namespace jewellery_project.Controllers
{
    public class User_newController : Controller
    {
        jewellary_dbEntities1 db = new jewellary_dbEntities1();
        // GET: /User_new/
        //-------------------------------------search---------------------
        [HttpPost]
        public ActionResult search(User ss)
        {
            return View();
        }
        //--------------------------------------------home------------------
        public ActionResult Home()
        {
            User df = new User();
            df.catlst = DBContext.getcat();
            df.collst = DBContext.getcol();
            int count_id = Convert.ToInt16(Session["u_id"]);
            var count_dt = (from j in db.tbl_cart where j.c_id == count_id select j).ToList();
            Session["count"] = count_dt.Count();
            return View(df);
        }
        //------------------------------------------reg----------------------
        public ActionResult Reg()
        {
            User df = new User();
            df.catlst = DBContext.getcat();
            df.collst = DBContext.getcol();
            stateBind(df);
            int count_id = Convert.ToInt16(Session["u_id"]);
            var count_dt = (from j in db.tbl_cart where j.c_id == count_id select j).ToList();
            Session["count"] = count_dt.Count();
            return View(df);
        }
        private void stateBind(User ss)
        {
            ss.states = new List<SelectListItem>();
            List<tbl_state> lc = db.tbl_state.ToList();
            foreach (var item in lc)
            {
                SelectListItem l = new SelectListItem();
                l.Text = item.name;
                l.Value = item.state_id.ToString();
                ss.states.Add(l);
            }
        }
        private static void cityBind(List<tbl_city> lc, List<SelectListItem> ls)
        {
            foreach (var item in lc)
            {
                SelectListItem l = new SelectListItem();
                l.Text = item.name;
                l.Value = item.city_id.ToString();
                ls.Add(l);
            }
        }
        [HttpPost]
        public ActionResult getcity(int stid)
        {
            List<tbl_city> lc = (from j in db.tbl_city where j.state_id == stid select j).ToList();
            List<SelectListItem> ls = new List<SelectListItem>();
            cityBind(lc, ls);
            return Json(ls, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Reg(User ss)
        {
            var email=ss.email;
            var mobile = ss.mobile;          
            int res;
            if ((int.TryParse(mobile, out res)) && (mobile.Length == 10))
            {
                if (email.Contains("@") && email.Contains(".com"))
                {
                    if (ss.password == ss.confirm_password)
                    {
                        tbl_user dt = new tbl_user();
                        dt.fname = ss.fname;
                        dt.mname = ss.mname;
                        dt.lname = ss.lname;
                        dt.gender = ss.gender;
                        dt.state_id = ss.state_id;
                        dt.city_id = ss.city_id;
                        dt.address = ss.address;
                        dt.mobile = ss.mobile;
                        dt.email = ss.email;
                        dt.password = ss.password;
                        dt.DOC = System.DateTime.Now;
                        dt.DOM = System.DateTime.Now;
                        db.tbl_user.Add(dt);
                        db.SaveChanges();
                        return RedirectToAction("Home");
                    }
                    else
                    {
                        ViewBag.conpass = "Password Doesn't Match";
                        User df = new User();
                        df.catlst = DBContext.getcat();
                        df.collst = DBContext.getcol();
                        stateBind(df);
                        df.city = new List<SelectListItem>();
                        List<tbl_city> lc = (from j in db.tbl_city where j.state_id == ss.state_id select j).ToList();
                        cityBind(lc, df.city);
                        int count_id = Convert.ToInt16(Session["u_id"]);
                        var count_dt = (from j in db.tbl_cart where j.c_id == count_id select j).ToList();
                        Session["count"] = count_dt.Count();
                        return View("Reg", df);
                    }
                }
                else
                {
                    ViewBag.email = "Email Is Not Valid";
                    User df = new User();
                    df.catlst = DBContext.getcat();
                    df.collst = DBContext.getcol();
                    stateBind(df);
                    df.city = new List<SelectListItem>();
                    List<tbl_city> lc = (from j in db.tbl_city where j.state_id == ss.state_id select j).ToList();
                    cityBind(lc, df.city);
                    int count_id = Convert.ToInt16(Session["u_id"]);
                    var count_dt = (from j in db.tbl_cart where j.c_id == count_id select j).ToList();
                    Session["count"] = count_dt.Count();
                    return View("Reg", df);
                }
            }
            else
            {
                ViewBag.mobile = "Mobile Number Is Not Valid";
                User df = new User();
                df.catlst = DBContext.getcat();
                df.collst = DBContext.getcol();
                stateBind(df);
                df.city = new List<SelectListItem>();
                List<tbl_city> lc = (from j in db.tbl_city where j.state_id == ss.state_id select j).ToList();
                cityBind(lc, df.city);
                int count_id = Convert.ToInt16(Session["u_id"]);
                var count_dt = (from j in db.tbl_cart where j.c_id == count_id select j).ToList();
                Session["count"] = count_dt.Count();
                return View("Reg", df);
            }           
        }
        //--------------------------------------------login-------------------------
        public ActionResult Login()
        {
            User df = new User();
            Session["forget"] = 0;
            df.catlst = DBContext.getcat();
            df.collst = DBContext.getcol();
            return View(df);
        }
        [HttpPost]
        public ActionResult Login(User ss)
        {
            User df = new User();
            df.catlst = DBContext.getcat();
            df.collst = DBContext.getcol();
           var email=ss.email;
           if (Convert.ToInt16(Session["forget"]) == 0)
           {
               if (email.Contains("@") && email.Contains(".com"))
               {
                   var obj = db.tbl_user.Where(a => a.email.Equals(ss.email) && a.password.Equals(ss.password)).FirstOrDefault();
                   if (obj != null)
                   {
                       if (obj.isActive == 1)
                       {
                           if (this.IsCaptchaValid("Captcha is not valid"))
                           {
                               Session["details"] = obj;
                               Session["fname"] = obj.fname;
                               Session["lname"] = obj.lname;
                               Session["u_id"] = obj.user_id;
                               Session["email"] = obj.email;
                               var obj1 = (from j in db.tbl_user
                                           join
                                               k in db.tbl_city on obj.city_id equals k.city_id
                                           join
                                                   l in db.tbl_state on obj.state_id equals l.state_id
                                           select new
                                           {
                                               city = k.name,
                                               state = l.name
                                           }).FirstOrDefault();
                               Session["address"] = obj.address + "," + obj1.city + "," + obj1.state;
                               if (Session["prev"] != null)
                               { 
                                   string prevurl=Session["prev"].ToString();
                                   return Redirect(prevurl);
                               }
                               else
                               {
                                   return RedirectToAction("Home");
                               }                             
                           }
                           else
                           {
                               ViewBag.ErrMessage = "Captcha is not valid.";
                               return View(df);
                           }
                       }
                       else
                       {
                           Response.Write("<script>alert('Unauthorized access')</script>");
                           return View(df);
                       }
                   }
                   else
                   {
                       Response.Write("<script>alert('Email Or Password Not Valid')</script>");
                       return View(df);
                   }
               }

jewellery_project/Views/User_new/Cart.cshtml
@model jewellery_project.Models.User
@{
    ViewBag.Title = "Cart";
    Layout = "~/Views/Shared/Usermaster.cshtml";
}

@using (Html.BeginForm("Cart", "User_new", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.cart_id)
    <!--banner-->
    <div class="banner-top">
        <div class="container">
            <h1>Cart</h1>
            <em></em>
            <h2><a href="@Url.Action("Home","User_new")">Home</a><label>/</label>Cart</h2>
        </div>
    </div>
    <!--login-->
    @*<script>
            $(document).ready(function (c) {
                $('.close1').on('click', function (c) {
                    $('.cart-header').fadeOut('slow', function (c) {
                        $('.cart-header').remove();
                    });
                });
            });
        </script>
        <script>
            $(document).ready(function (c) {
                $('.close2').on('click', function (c) {
                    $('.cart-header1').fadeOut('slow', function (c) {
                        $('.cart-header1').remove();
                    });
                });
            });
        </script>
        <script>
            $(document).ready(function (c) {
                $('.close3').on('click', function (c) {
                    $('.cart-header2').fadeOut('slow', function (c) {
                        $('.cart-header2').remove();
                    });
                });
            });
        </script>*@
    <div class="check-out">
        <div class="container">

            <div class="bs-example4" data-example-id="simple-responsive-table">
                <div class="table-responsive">
                    <table class="table-heading simpleCart_shelfItem">
                        <tr>
                            <th class="table-grid">Item</th>

                            <th>Prices</th>
                            <th>Delivery </th>
                            <th>Quantity</th>
                            <th>Subtotal</th>

                        </tr>

                        @foreach (var item in Model.cartitems)
                        {
                            <tr class="cart-header">

                                <td class="ring-in">
                                    <a href="@Url.Action("viewproductdetails", "User_new", new { @id = item.p_id })" class="at-in"><img src="@Url.Content(item.image)" class="img-responsive" alt=""></a>
                                    <div class="sed">
                                        <h5><a href="@Url.Action("viewproductdetails", "User_new", new { @id = item.p_id })">@item.name</a></h5>

                                    </div>
                                    <div class="clearfix"> </div>


                                </td>
                                <td>@item.price</td>
                                <td>FREE SHIPPING</td>
                                <td>
                                    <div class="quantity">
                                        <div class="quantity-select">


                                            <button type="button" id="sub" class="sub btn" style="float:left" onclick="location.href='@Url.Action("minusquantity", "User_new", new { @id = item.cart_id,@q=item.quantity,@p=item.price })'"><span class="glyphicon glyphicon-minus"></span></button>

                                            @Html.TextBoxFor(m => m.quantity, new { @Value = item.quantity, @id = "1", @class = "field form-control", style = "width:40px;float:left;margin-left:7px;margin-right:7px" })
                                            <button type="button" id="add" class="add btn" onclick="location.href='@Url.Action("plusquantity", "User_new", new { @id = item.cart_id,@q=item.quantity,@p=item.price })'"><span class="glyphicon glyphicon-plus"></span></button>


                                        </div>
                                    </div>
                                </td>
                                <td class="item_price">@item.total</td>
                                <td>
                                    <a href="@Url.Action("removecartitem", "User_new", new { @id = item.cart_id })"><i class="glyphicon glyphicon-remove-circle" style="color: #f67777; font-size: 30px"></i></a>
                                </td>
                            </tr>

                        }

                    </table>
                </div>
            </div>
            <div class="produced">
                <a href="@Url.Action("cartchecking", "User_new")" class="hvr-skew-backward">Produced To Buy</a>
            </div>
        </div>
    </div>
    <br />
    <br />
    <!--//login-->
}
<script>
    var unit = document.getElementById("1").value;
    var total;
    $('.field').change(function () {
        unit = this.value;
    });
    $('.add').click(function () {
        if (unit < 10) {
            unit++;
            var $input = $(this).prevUntil('.sub');
            $input.val(unit);
            unit = unit;
        }
    });
    $('.sub').click(function () {
        if (unit > 1) {
            unit--;
            var $input = $(this).nextUntil('.add');
            $input.val(unit);
        }
    });
</script>

@*<script>
    $(function () {
        $('.add').click(function () {
            var ipvalue = $("#IP").val();
            this.href = this.href.replace("xxx", ipvalue);
        });
    });
</script>*@


jewellery_project/Views/User_new/Custom_made.cshtml
@model jewellery_project.Models.User
@{
    ViewBag.Title = "Custom_made";
    Layout = "~/Views/Shared/Usermaster.cshtml";
}

@using (Html.BeginForm("Custom_made", "User_new", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.user_id)
    <!--banner-->
    <div class="banner-top">
        <div class="container">
            <h1>Custom Made</h1>
            <em></em>
            <h2><a href="@Url.Action("Home","User_new")">Home</a><label>/</label>Custom Made</h2>
        </div>
    </div>
    <!--login-->
    <div class="container">
        <div class="login">
            <form>
                <div class="col-md-6 login-do">
                    <div class="login-mail">
                        @*<input type="text" placeholder="Name" required="">*@
                        @Html.TextBoxFor(m => m.name, new { @placeholder = "Name", @required="" })
                    </div>
                    <p style="color:red">@ViewBag.email</p>

                    <div class="login-mail">
                        @Html.TextBoxFor(m => m.email, new { @placeholder = "Email", @required = "" })
                    </div>
                    <p style="color:red">@ViewBag.mobile</p>

                    <div class="login-mail">

                        @Html.TextBoxFor(m => m.mobile, new { @placeholder = "Mobile Number", @required = "" })

                    </div>
                    <div class="login-mail">

                        @Html.TextBoxFor(m => m.subject, new { @placeholder = "Subject", @required = "" })

                    </div>
                    <div class="login-mail">

                        <input type="file" name="ffl" id="src" required />
                        <img id="target" height="100" width="100" />


                    </div>
                    <div>
                        @Html.TextAreaFor(m => m.message, new { @placeholder = "message", @class = "form-control", rows = "3", @required = "" })

                    </div><br />
                   
                  
                    <label class="hvr-skew-backward">
                        <input type="submit" value="Submit">
                    </label>

                </div>
                <div class="col-md-6 login-right">
                    <h3>Details</h3>

                    <p>
                        Buying custom product is not a new concept that’s how everything used to be. Now big stores, online retailers and local jewellers have made standardization (boring) and low prices (low quality) the rule of the day.
                        We’re here to change the rules back.</p>

                </div>

                <div class="clearfix"> </div>
            </form>
        </div>

    </div>
    <br />
    <br />
}

<script>
    function showImage(src, target) {
        var fr = new FileReader();
        fr.onload = function (e) { target.src = this.result; };
        src.addEventListener("change", function () {
            fr.readAsDataURL(src.files[0]);
        });
    }
    var src = document.getElementById("src");
    var target = document.getElementById("target");
    showImage(src, target);
</script>



jewellery_project/Views/User_new/Home.cshtml

@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/Usermaster.cshtml";
}

  <!--banner-->
<div class="banner">
    <div class="container">
        <section class="rw-wrapper">
            <h1 class="rw-sentence">
                <span style="color:white;text-align:end">Diamond is forever</span>
                
                @*<div class="rw-words rw-words-1">
                    <span style="color: white; text-align: end">Your idea,Our Creation</span>
                    <span style="color: white; text-align: end">Righteous Selections.</span>
                    <span style="color: white; text-align: end">Rock Solid Elegance.</span>
                    <span style="color: white; text-align: end">Jewelry that speaks for itself.</span>
                    <span style="color: white; text-align: end">Rock Your Jewelry.</span>
                    <span style="color: white; text-align: end">Stylish and Sophisticated Sparkle.</span>
                </div>*@
                <div class="rw-words rw-words-2">
                    <span style="text-align:end">Accentuate Your Shine</span>
                    <span style="text-align:end">right and Shiny, Bold and Beautiful</span>
                    <span style="text-align:end">Sparkle That Brings Out The Luxury In You</span>
                    <span style="text-align:end">Bedazzled by your soulstone</span>
                    <span style="text-align:end">Always the crowning jewel</span>
                    <span style="text-align:end">Sparkle and shine day and night </span>
                </div>
            </h1>
        </section>
    </div>
</div>
<!--content-->
<div class="content">
    <div class="container">
        <div class="content-top">
            <div class="col-md-6 col-md">
                <div class="col-1">
                    <a href="@Url.Action("viewcolwiseprod", "User_new", new { @id = 2 })" class="b-link-stroke b-animate-go  thickbox">
                        <img src="/User/images/bridal.jpg" class="img-responsive" alt="" /><div class="b-wrapper1 long-img"><p class="b-animate b-from-right    b-delay03 ">Trendy</p><label class="b-animate b-from-right    b-delay03 "></label><h3 class="b-animate b-from-left    b-delay03 ">Bridal Set</h3></div>
                    </a>
                    
                    <!---<a href="single.html"><img src="images/pi.jpg" class="img-responsive" alt=""></a>-->
                </div>
                <div class="col-2">
                    <span>Hot Deal</span>
                    <h2>Luxurious &amp; Trendy</h2>
                    <p>Jewelry is a wonderful way of displaying our favorite gems. Or perhaps a lovely charm. Or something a special someone gave you. Whichever way, we can admit that it's very special. So it would only figure that the ancient civilization of Rome would decorate their necks, ears, and wrists with elaborate and gorgeous accessories. However, what kind of jewelry did they wear.     
</p>
                </div>
            </div>
            <div class="col-md-6 col-md1">
                <div class="col-3">
                    <a href="@Url.Action("viewcolwiseprod", "User_new", new { @id = 7 })">
                        <img src="/User/images/platinum.jpg" class="img-responsive" alt="">
                        <div class="col-pic">
                            <p>Trendy</p>
                            <label></label>
                            <h5>Platinum Jewellary</h5>
                        </div>
                    </a>
                </div>
                <div class="col-3">
                    <a href="@Url.Action("viewcolwiseprod", "User_new", new { @id = 6 })">
                        <img src="/User/images/gemstone.jpg" class="img-responsive" alt="">
                        <div class="col-pic">
                            <p>Trendy</p>
                            <label></label>
                            <h5>Gemstone Jewellary</h5>
                        </div>
                    </a>
                </div>
                <div class="col-3">
                    <a href="@Url.Action("viewcolwiseprod", "User_new", new { @id = 5 })">
                        <img src="/User/images/novelty.jpg" class="img-responsive" alt="">
                        <div class="col-pic">
                            <p>Trendy</p>
                            <label></label>
                            <h5>Novelty Jewellary</h5>
                        </div>
                    </a>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <!--products-->
        
        <!--//products-->
      
    </div>

</div>
<!--//content-->


jewellery_project/Views/User_new/Login.cshtml
@using CaptchaMvc.HtmlHelpers
@using jewellery_project;
@using CaptchaMvc;
@model jewellery_project.Models.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/Usermaster.cshtml";
}
@using (Html.BeginForm("Login", "User_new", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.user_id)
    <!--banner-->
    <div class="banner-top">
        <div class="container">
            <h1>Login</h1>
            <em></em>
            <h2><a href="@Url.Action("Home","User_new")">Home</a><label>/</label>Login</h2>
        </div>
    </div>
    <!--login-->
    <div class="container">
        <div class="login">

            <form>
                <div class="col-md-6 login-do">
                    @if (Convert.ToInt16(Session["forget"]) == 0)
                    {
//@Html.ValidationMessageFor(m => m.email, "", new { @class = "text-danger" })
                        <p style="color:red">@ViewBag.emaillog</p>

                        <div class="login-mail">

                            @Html.TextBoxFor(m => m.email, new { @placeholder = "Email",@required=""})
                           
                            
                            <i class="glyphicon glyphicon-envelope"></i>
                        </div>
                     //   @Html.ValidationMessageFor(m => m.password, "", new { @class = "text-danger" })

                        <div class="login-mail">
                            @Html.PasswordFor(m => m.password, new { @placeholder = "Password" ,@required=""})
                            <i class="glyphicon glyphicon-lock"></i>

                        </div>

                        <div class="form-group">
                            @Html.Captcha(4)
                            <p class="Error" style="color:red;">  @ViewBag.ErrMessage </p>
                        </div>
                        <a class="news-letter " href="@Url.Action("forgetpassword","User_new")">
                            Forget Password
                        </a>
                    }
                    else
                    {
                        @Html.ValidationMessageFor(m => m.email, "", new { @class = "text-danger" })

                        <div class="login-mail">
                            @Html.TextBoxFor(m => m.email, new { @placeholder = "Enter Registered Email" })
                            <i class="glyphicon glyphicon-envelope"></i>
                        </div>
                    }
                    <label class="hvr-skew-backward">
                        <input type="submit" value="Submit">
                    </label>
                </div>
                <div class="col-md-6 login-right">
                    <h3>Completely Free Account</h3>

                    <p>
                        Get Yourself Register Now To Be the first to know about our latest offers and new collections.By getting registered,you agree with the terms & condition of our site.
                        Through registerd,We Will able to contact With You in a right way.By creating an account you will be able to shop faster and receive regular updates on Products.

                    </p>
                    <a href="@Url.Action("Reg","User_new")" class=" hvr-skew-backward">Register</a>

                </div>

                <div class="clearfix"> </div>
            </form>
        </div>

    </div>
    <br />
    <br />
    <!--//login-->
}


jewellery_project/Views/User_new/Orderconfirm.cshtml
@model jewellery_project.Models.User
@{
    ViewBag.Title = "Orderconfirm";
    Layout = "~/Views/Shared/Usermaster.cshtml";
}

@using (Html.BeginForm("Orderconfirm", "User_new", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="banner-top">
        <div class="container">
            <h1>Confirmation</h1>
            <em></em>
            <h2><a href="@Url.Action("Home","User_new")">Home</a><label>/</label>Confirmation</h2>
        </div>
    </div>
    
    <div class="container">
        <div class="page">
            <div class="grid_3 grid_4">
                <div class="page-header">
                    <h1 style="font-weight: bold; color: #f67777">Order Id:@Session["Order_id"]</h1>
                    <p style="color:green">Your Order is Successfully Placed..Thank You</p>
                    <br />
                    <br />
                    <a href="@Url.Action("Invoice", "User_new")" class="btn btn-lg btn-default" style="background-color:#f67777;color:white">View Invoice</a>

                </div>
            </div>
        </div>
    </div>
}


jewellery_project/Views/User_new/addressedit.cshtml
@model jewellery_project.Models.User

@using (Html.BeginForm("Orderdetails", "User_new", FormMethod.Post))
{
    <div class="container" style="background-color:white; width:40%; border-radius:10px; margin:auto;">
        <br />
        @Html.HiddenFor(m => m.user_id)
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-9">
                <div class="row">
                    <a href="#" data-dismiss="modal" class="close">&times;</a>
                </div>
                <br />

                <div class="row">
                    <label for="poffer">Delivery Address</label>
                    @Html.TextAreaFor(m => m.address, new { @class = "form-control",@required="" })
                    @Html.ValidationMessageFor(m => m.address, "", new { @class = "text-danger" })


                </div>
               

                <br />
                <div class="row">

                    <input type="submit" name="command" value="Save Change" class="btn btn-primary" />
                </div>
            </div>
            <div class="col-sm-1"></div>
        </div>
        <br />
    </div>

}